"""The flake escape hatch: a toolbelt Nixery refuses, built on the machine by a nix
builder container from a flake generated from its package list — never written by a person or
an agent.

Its whole domain is unfree packages: Nixery never builds one, and a name nixpkgs does not have
fails here as it does there. Unfree is allowed; whether a toolbelt uses one is the user's
choice. Nothing unfree is in
NixOS's binary cache, so such a package is compiled here, which can take many minutes.

A package name is checked against a plain attribute-path pattern and handed to Nix as a
string, then looked up with `lib.getAttrFromPath`: nothing a toolbelt says is Nix code.
The nixpkgs revision the first build used is kept in the toolbelt's lock, so a rebuild on any
machine asks for the same one.
"""
from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path

from . import labels, naming
from .definitions import Toolbelt
from .runtime.base import ContainerRuntime, ContainerSpec, Mount

UNSTABLE = "github:NixOS/nixpkgs/nixpkgs-unstable"
_NAME = re.compile(r"[A-Za-z_][A-Za-z0-9_+-]*(\.[A-Za-z_][A-Za-z0-9_+-]*)*")
_REV = re.compile(r"[0-9a-f]{40}")
_ID = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]*")
# What Nixery's `shell` meta-package gives every image, and what the view's closure copy runs.
BASE = ("bashInteractive", "coreutils")


class FlakeError(RuntimeError):
    pass


def generate(toolbelt: Toolbelt, rev: str | None = None, tag: str = "unpinned") -> str:
    """The flake for `toolbelt`: its packages over `BASE`, as a layered image whose `/bin` and
    `/nix/store` are the shape a Nixery image has (`closures.py`)."""
    if not _ID.fullmatch(toolbelt.id):
        raise FlakeError(f"toolbelt id {toolbelt.id!r} cannot name a flake: letters, digits, "
                         "'.', '_' and '-' only")
    for name in toolbelt.packages:
        if not _NAME.fullmatch(name):
            raise FlakeError(f"toolbelt '{toolbelt.id}' names {name!r}, which is not a nixpkgs "
                             "attribute path")
    if rev is not None and not _REV.fullmatch(rev):
        raise FlakeError(f"{rev!r} is not a nixpkgs commit")
    url = f"github:NixOS/nixpkgs/{rev}" if rev else UNSTABLE
    names = json.dumps([*BASE, *(p for p in toolbelt.packages if p not in BASE)])
    return f'''# Generated by raigolmid from toolbelt "{toolbelt.id}"; never edited.
{{
  inputs.nixpkgs.url = "{url}";
  outputs = {{ self, nixpkgs }}:
    let
      pkgs = import nixpkgs {{ system = "x86_64-linux"; config.allowUnfree = true; }};
      named = map (n: pkgs.lib.getAttrFromPath (pkgs.lib.splitString "." n) pkgs)
        (builtins.fromJSON {json.dumps(names)});
    in {{
      packages.x86_64-linux.default = pkgs.dockerTools.streamLayeredImage {{
        name = "raigolmid/toolbelt-{toolbelt.id}";
        tag = "{tag}";
        contents = [ (pkgs.buildEnv {{ name = "toolbelt-{toolbelt.id}"; paths = named; }}) ];
      }};
    }};
}}
'''


def locked_rev(flake_lock: str) -> str:
    """The nixpkgs commit a build resolved to, from the `flake.lock` nix wrote beside it."""
    try:
        rev = json.loads(flake_lock)["nodes"]["nixpkgs"]["locked"]["rev"]
    except (json.JSONDecodeError, KeyError, TypeError) as exc:
        raise FlakeError(f"flake.lock names no nixpkgs revision: {exc}") from exc
    if not _REV.fullmatch(rev):
        raise FlakeError(f"flake.lock's nixpkgs revision {rev!r} is not a commit")
    return rev


# --- the build ------------------------------------------------------------------------------

BUILDER = "docker.io/nixos/nix:latest"
# The builder's store, a volume: it outlives each build, so a second one fetches nothing twice.
STORE_VOLUME = "raigolmid-nix"
# A package compiled from source (every unfree one) is minutes, a large one many.
BUILD_SECONDS = 3600
NIX = "nix --extra-experimental-features 'nix-command flakes'"


@dataclass(frozen=True, slots=True)
class Built:
    """What a flake build made: the image, and the nixpkgs it was built from."""
    image: str
    nixpkgs: str
    package_digest: str

    def to_dict(self) -> dict[str, str]:
        return {"image": self.image, "nixpkgs": self.nixpkgs,
                "package_digest": self.package_digest}


def record_of(directory: Path, toolbelt: Toolbelt) -> Built | None:
    """The build made for this package list, if there is one."""
    path = directory / toolbelt.id / "built.json"
    if not path.is_file():
        return None
    raw = json.loads(path.read_text())
    built = Built(image=raw["image"], nixpkgs=raw["nixpkgs"],
                  package_digest=raw["package_digest"])
    return built if built.package_digest == toolbelt.package_digest else None


def build(runtime: ContainerRuntime, directory: Path, toolbelt: Toolbelt,
          nixpkgs: str | None, epoch: int) -> Built:
    """The toolbelt as an image on this machine, from nixpkgs at `nixpkgs`, or at the newest
    unstable commit, which the build then pins. Two runs of the builder: the first locks an
    unpinned nixpkgs to a commit, the second builds from a flake naming that commit, so the
    image is named by exactly what it was built from."""
    work = directory / toolbelt.id
    work.mkdir(parents=True, exist_ok=True)
    if runtime.image(BUILDER) is None:
        runtime.pull(BUILDER)
    if nixpkgs is None:
        (work / "flake.nix").write_text(generate(toolbelt))
        (work / "flake.lock").unlink(missing_ok=True)
        _run(runtime, work, f"{NIX} flake lock", epoch)
        nixpkgs = locked_rev((work / "flake.lock").read_text())
    # Named by what it is built from: the same list at the same commit is the same tag.
    tag = "sha256-" + hashlib.sha256(generate(toolbelt, nixpkgs).encode()).hexdigest()[:12]
    (work / "flake.nix").write_text(generate(toolbelt, nixpkgs, tag))
    image = f"raigolmid/toolbelt-{toolbelt.id}:{tag}"
    tar = work / "image.tar"
    tar.unlink(missing_ok=True)
    _run(runtime, work, f"{NIX} build --no-link --print-out-paths .#default > /src/out "
                        "&& \"$(cat /src/out)\" > /src/image.tar", epoch)
    loaded = runtime.load(tar)
    tar.unlink()
    if image not in loaded:
        raise FlakeError(f"the flake built {', '.join(loaded) or 'nothing'}, not {image}")
    built = Built(image=image, nixpkgs=nixpkgs, package_digest=toolbelt.package_digest)
    (work / "built.json").write_text(json.dumps(built.to_dict()))
    return built


def _run(runtime: ContainerRuntime, work: Path, script: str, epoch: int) -> None:
    name = naming.flake_build()
    if runtime.inspect(name) is not None:
        runtime.remove(name, force=True)
    result = runtime.run_to_completion(ContainerSpec(
        name=name, image=BUILDER, command=("sh", "-c", script), working_dir="/src",
        labels={labels.MANAGED: "true", labels.ROLE: str(labels.Role.FLAKE_BUILD),
                labels.EPOCH: str(epoch)},
        mounts=(Mount(source=STORE_VOLUME, target="/nix", volume=True),
                Mount(source=str(work), target="/src")),
    ), BUILD_SECONDS)
    if result.exit_code != 0:
        raise FlakeError(f"nix exited {result.exit_code}: {result.output.strip()[-3000:]}")
